name: Docker CI with Logs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t logger .
      
    - name: Run container
      run: |
        mkdir -p logs
        docker run --rm -v $(pwd)/logs:/home/logs logger > logs/output.log 2>&1
        
    - name: Upload logs
      uses: actions/upload-artifact@v4  
      with:
        name: logs
        path: logs/output.txt
