name: Docker CI with Logs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t hello-world-app .
      
    - name: Run container and capture logs
      run: |
        mkdir -p logs
        docker run \
          --rm \
          -v $(pwd)/logs:/home/logs \
          hello-world-app > logs/output.log 2>&1
        
    - name: Upload logs
      uses: actions/upload-artifact@v4  # Changed from v3 to v4
      with:
        name: application-logs
        path: |
          logs/output.log
          logs/log.txt
